export const PERTINENT_BOOK_SUBJECTS = [
    "Science Fiction",
    "Fantasy",
    "Mystery",
    "Thriller",
    "Romance",
    "Historical Fiction",
    "Non-Fiction",
    "Biography",
    "Self-Help",
    "Health & Wellness",
    "Cookbooks",
    "Travel",
    "Children's Books",
    "Young Adult",
    "Graphic Novels & Comics",
    "Death",
    "Life",
    "Sorciers",
    "Sorcières",
    "Fiction",
    "Science",
    "Philosophy",
    "Psychology",
    "Sociology",
    "Anthropology",
    "Economics",
    "Finance",
    "Politics",
    "History",
]